/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersShareableFileRequest
 */
export interface HandlersShareableFileRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileRequest
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileRequest
     */
    fileName: string;
    /**
     * 
     * @type {number}
     * @memberof HandlersShareableFileRequest
     */
    fileSize: number;
}

/**
 * Check if a given object implements the HandlersShareableFileRequest interface.
 */
export function instanceOfHandlersShareableFileRequest(value: object): value is HandlersShareableFileRequest {
    if (!('contentType' in value) || value['contentType'] === undefined) return false;
    if (!('fileName' in value) || value['fileName'] === undefined) return false;
    if (!('fileSize' in value) || value['fileSize'] === undefined) return false;
    return true;
}

export function HandlersShareableFileRequestFromJSON(json: any): HandlersShareableFileRequest {
    return HandlersShareableFileRequestFromJSONTyped(json, false);
}

export function HandlersShareableFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersShareableFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['content_type'],
        'fileName': json['file_name'],
        'fileSize': json['file_size'],
    };
}

export function HandlersShareableFileRequestToJSON(json: any): HandlersShareableFileRequest {
    return HandlersShareableFileRequestToJSONTyped(json, false);
}

export function HandlersShareableFileRequestToJSONTyped(value?: HandlersShareableFileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': value['contentType'],
        'file_name': value['fileName'],
        'file_size': value['fileSize'],
    };
}

