/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServicesTargetUserEmails } from './ServicesTargetUserEmails';
import {
    ServicesTargetUserEmailsFromJSON,
    ServicesTargetUserEmailsFromJSONTyped,
    ServicesTargetUserEmailsToJSON,
    ServicesTargetUserEmailsToJSONTyped,
} from './ServicesTargetUserEmails';

/**
 * 
 * @export
 * @interface HandlersTargetUserEmailResponse
 */
export interface HandlersTargetUserEmailResponse {
    /**
     * 
     * @type {Array<ServicesTargetUserEmails>}
     * @memberof HandlersTargetUserEmailResponse
     */
    history?: Array<ServicesTargetUserEmails>;
}

/**
 * Check if a given object implements the HandlersTargetUserEmailResponse interface.
 */
export function instanceOfHandlersTargetUserEmailResponse(value: object): value is HandlersTargetUserEmailResponse {
    return true;
}

export function HandlersTargetUserEmailResponseFromJSON(json: any): HandlersTargetUserEmailResponse {
    return HandlersTargetUserEmailResponseFromJSONTyped(json, false);
}

export function HandlersTargetUserEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersTargetUserEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'history': json['history'] == null ? undefined : ((json['history'] as Array<any>).map(ServicesTargetUserEmailsFromJSON)),
    };
}

export function HandlersTargetUserEmailResponseToJSON(json: any): HandlersTargetUserEmailResponse {
    return HandlersTargetUserEmailResponseToJSONTyped(json, false);
}

export function HandlersTargetUserEmailResponseToJSONTyped(value?: HandlersTargetUserEmailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'history': value['history'] == null ? undefined : ((value['history'] as Array<any>).map(ServicesTargetUserEmailsToJSON)),
    };
}

