/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersShareableFileUpload
 */
export interface HandlersShareableFileUpload {
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileUpload
     */
    fileId?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileUpload
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileUpload
     */
    uploadUrl?: string;
}

/**
 * Check if a given object implements the HandlersShareableFileUpload interface.
 */
export function instanceOfHandlersShareableFileUpload(value: object): value is HandlersShareableFileUpload {
    return true;
}

export function HandlersShareableFileUploadFromJSON(json: any): HandlersShareableFileUpload {
    return HandlersShareableFileUploadFromJSONTyped(json, false);
}

export function HandlersShareableFileUploadFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersShareableFileUpload {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'uploadUrl': json['upload_url'] == null ? undefined : json['upload_url'],
    };
}

export function HandlersShareableFileUploadToJSON(json: any): HandlersShareableFileUpload {
    return HandlersShareableFileUploadToJSONTyped(json, false);
}

export function HandlersShareableFileUploadToJSONTyped(value?: HandlersShareableFileUpload | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_id': value['fileId'],
        'file_name': value['fileName'],
        'upload_url': value['uploadUrl'],
    };
}

