/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreateShareableRequestTimeParams
 */
export interface HandlersCreateShareableRequestTimeParams {
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateShareableRequestTimeParams
     */
    activeFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateShareableRequestTimeParams
     */
    expiryAt?: string;
}

/**
 * Check if a given object implements the HandlersCreateShareableRequestTimeParams interface.
 */
export function instanceOfHandlersCreateShareableRequestTimeParams(value: object): value is HandlersCreateShareableRequestTimeParams {
    return true;
}

export function HandlersCreateShareableRequestTimeParamsFromJSON(json: any): HandlersCreateShareableRequestTimeParams {
    return HandlersCreateShareableRequestTimeParamsFromJSONTyped(json, false);
}

export function HandlersCreateShareableRequestTimeParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateShareableRequestTimeParams {
    if (json == null) {
        return json;
    }
    return {
        
        'activeFrom': json['active_from'] == null ? undefined : json['active_from'],
        'expiryAt': json['expiry_at'] == null ? undefined : json['expiry_at'],
    };
}

export function HandlersCreateShareableRequestTimeParamsToJSON(json: any): HandlersCreateShareableRequestTimeParams {
    return HandlersCreateShareableRequestTimeParamsToJSONTyped(json, false);
}

export function HandlersCreateShareableRequestTimeParamsToJSONTyped(value?: HandlersCreateShareableRequestTimeParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_from': value['activeFrom'],
        'expiry_at': value['expiryAt'],
    };
}

