/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HandlersShareableFileResponse } from './HandlersShareableFileResponse';
import {
    HandlersShareableFileResponseFromJSON,
    HandlersShareableFileResponseFromJSONTyped,
    HandlersShareableFileResponseToJSON,
    HandlersShareableFileResponseToJSONTyped,
} from './HandlersShareableFileResponse';

/**
 * 
 * @export
 * @interface HandlersGetShareableResponse
 */
export interface HandlersGetShareableResponse {
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    activeFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    data?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    expiryAt?: string;
    /**
     * 
     * @type {Array<HandlersShareableFileResponse>}
     * @memberof HandlersGetShareableResponse
     */
    files?: Array<HandlersShareableFileResponse>;
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof HandlersGetShareableResponse
     */
    options?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    userEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGetShareableResponse
     */
    userId?: string;
}

/**
 * Check if a given object implements the HandlersGetShareableResponse interface.
 */
export function instanceOfHandlersGetShareableResponse(value: object): value is HandlersGetShareableResponse {
    return true;
}

export function HandlersGetShareableResponseFromJSON(json: any): HandlersGetShareableResponse {
    return HandlersGetShareableResponseFromJSONTyped(json, false);
}

export function HandlersGetShareableResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersGetShareableResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'activeFrom': json['active_from'] == null ? undefined : json['active_from'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'data': json['data'] == null ? undefined : json['data'],
        'expiryAt': json['expiry_at'] == null ? undefined : json['expiry_at'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(HandlersShareableFileResponseFromJSON)),
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'options': json['options'] == null ? undefined : json['options'],
        'type': json['type'] == null ? undefined : json['type'],
        'userEmail': json['user_email'] == null ? undefined : json['user_email'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function HandlersGetShareableResponseToJSON(json: any): HandlersGetShareableResponse {
    return HandlersGetShareableResponseToJSONTyped(json, false);
}

export function HandlersGetShareableResponseToJSONTyped(value?: HandlersGetShareableResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active_from': value['activeFrom'],
        'created_at': value['createdAt'],
        'data': value['data'],
        'expiry_at': value['expiryAt'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(HandlersShareableFileResponseToJSON)),
        'id': value['id'],
        'name': value['name'],
        'options': value['options'],
        'type': value['type'],
        'user_email': value['userEmail'],
        'user_id': value['userId'],
    };
}

