/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersGoogleCallbackResponse
 */
export interface HandlersGoogleCallbackResponse {
    /**
     * 
     * @type {string}
     * @memberof HandlersGoogleCallbackResponse
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGoogleCallbackResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGoogleCallbackResponse
     */
    id?: string;
}

/**
 * Check if a given object implements the HandlersGoogleCallbackResponse interface.
 */
export function instanceOfHandlersGoogleCallbackResponse(value: object): value is HandlersGoogleCallbackResponse {
    return true;
}

export function HandlersGoogleCallbackResponseFromJSON(json: any): HandlersGoogleCallbackResponse {
    return HandlersGoogleCallbackResponseFromJSONTyped(json, false);
}

export function HandlersGoogleCallbackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersGoogleCallbackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function HandlersGoogleCallbackResponseToJSON(json: any): HandlersGoogleCallbackResponse {
    return HandlersGoogleCallbackResponseToJSONTyped(json, false);
}

export function HandlersGoogleCallbackResponseToJSONTyped(value?: HandlersGoogleCallbackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'email': value['email'],
        'id': value['id'],
    };
}

