/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HandlersShareableFileUpload } from './HandlersShareableFileUpload';
import {
    HandlersShareableFileUploadFromJSON,
    HandlersShareableFileUploadFromJSONTyped,
    HandlersShareableFileUploadToJSON,
    HandlersShareableFileUploadToJSONTyped,
} from './HandlersShareableFileUpload';

/**
 * 
 * @export
 * @interface HandlersCreateShareableResponse
 */
export interface HandlersCreateShareableResponse {
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateShareableResponse
     */
    code?: string;
    /**
     * only present for file type
     * @type {Array<HandlersShareableFileUpload>}
     * @memberof HandlersCreateShareableResponse
     */
    uploads?: Array<HandlersShareableFileUpload>;
}

/**
 * Check if a given object implements the HandlersCreateShareableResponse interface.
 */
export function instanceOfHandlersCreateShareableResponse(value: object): value is HandlersCreateShareableResponse {
    return true;
}

export function HandlersCreateShareableResponseFromJSON(json: any): HandlersCreateShareableResponse {
    return HandlersCreateShareableResponseFromJSONTyped(json, false);
}

export function HandlersCreateShareableResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateShareableResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'uploads': json['uploads'] == null ? undefined : ((json['uploads'] as Array<any>).map(HandlersShareableFileUploadFromJSON)),
    };
}

export function HandlersCreateShareableResponseToJSON(json: any): HandlersCreateShareableResponse {
    return HandlersCreateShareableResponseToJSONTyped(json, false);
}

export function HandlersCreateShareableResponseToJSONTyped(value?: HandlersCreateShareableResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'uploads': value['uploads'] == null ? undefined : ((value['uploads'] as Array<any>).map(HandlersShareableFileUploadToJSON)),
    };
}

