/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersShareableFileResponse
 */
export interface HandlersShareableFileResponse {
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileResponse
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileResponse
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileResponse
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileResponse
     */
    shareId?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersShareableFileResponse
     */
    signedUrl?: string;
}

/**
 * Check if a given object implements the HandlersShareableFileResponse interface.
 */
export function instanceOfHandlersShareableFileResponse(value: object): value is HandlersShareableFileResponse {
    return true;
}

export function HandlersShareableFileResponseFromJSON(json: any): HandlersShareableFileResponse {
    return HandlersShareableFileResponseFromJSONTyped(json, false);
}

export function HandlersShareableFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersShareableFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'contentType': json['content_type'] == null ? undefined : json['content_type'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'fileName': json['file_name'] == null ? undefined : json['file_name'],
        'id': json['id'] == null ? undefined : json['id'],
        'shareId': json['share_id'] == null ? undefined : json['share_id'],
        'signedUrl': json['signed_url'] == null ? undefined : json['signed_url'],
    };
}

export function HandlersShareableFileResponseToJSON(json: any): HandlersShareableFileResponse {
    return HandlersShareableFileResponseToJSONTyped(json, false);
}

export function HandlersShareableFileResponseToJSONTyped(value?: HandlersShareableFileResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content_type': value['contentType'],
        'created_at': value['createdAt'],
        'file_name': value['fileName'],
        'id': value['id'],
        'share_id': value['shareId'],
        'signed_url': value['signedUrl'],
    };
}

