/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersGoogleLoginResponse
 */
export interface HandlersGoogleLoginResponse {
    /**
     * 
     * @type {string}
     * @memberof HandlersGoogleLoginResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the HandlersGoogleLoginResponse interface.
 */
export function instanceOfHandlersGoogleLoginResponse(value: object): value is HandlersGoogleLoginResponse {
    return true;
}

export function HandlersGoogleLoginResponseFromJSON(json: any): HandlersGoogleLoginResponse {
    return HandlersGoogleLoginResponseFromJSONTyped(json, false);
}

export function HandlersGoogleLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersGoogleLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function HandlersGoogleLoginResponseToJSON(json: any): HandlersGoogleLoginResponse {
    return HandlersGoogleLoginResponseToJSONTyped(json, false);
}

export function HandlersGoogleLoginResponseToJSONTyped(value?: HandlersGoogleLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

