/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreateShareableRequestNotificationParams
 */
export interface HandlersCreateShareableRequestNotificationParams {
    /**
     * 
     * @type {boolean}
     * @memberof HandlersCreateShareableRequestNotificationParams
     */
    emailNotificationOnOpen?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HandlersCreateShareableRequestNotificationParams
     */
    notifyTargetEmails?: boolean;
}

/**
 * Check if a given object implements the HandlersCreateShareableRequestNotificationParams interface.
 */
export function instanceOfHandlersCreateShareableRequestNotificationParams(value: object): value is HandlersCreateShareableRequestNotificationParams {
    return true;
}

export function HandlersCreateShareableRequestNotificationParamsFromJSON(json: any): HandlersCreateShareableRequestNotificationParams {
    return HandlersCreateShareableRequestNotificationParamsFromJSONTyped(json, false);
}

export function HandlersCreateShareableRequestNotificationParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateShareableRequestNotificationParams {
    if (json == null) {
        return json;
    }
    return {
        
        'emailNotificationOnOpen': json['email_notification_on_open'] == null ? undefined : json['email_notification_on_open'],
        'notifyTargetEmails': json['notify_target_emails'] == null ? undefined : json['notify_target_emails'],
    };
}

export function HandlersCreateShareableRequestNotificationParamsToJSON(json: any): HandlersCreateShareableRequestNotificationParams {
    return HandlersCreateShareableRequestNotificationParamsToJSONTyped(json, false);
}

export function HandlersCreateShareableRequestNotificationParamsToJSONTyped(value?: HandlersCreateShareableRequestNotificationParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email_notification_on_open': value['emailNotificationOnOpen'],
        'notify_target_emails': value['notifyTargetEmails'],
    };
}

