/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HandlersShareableFileRequest } from './HandlersShareableFileRequest';
import {
    HandlersShareableFileRequestFromJSON,
    HandlersShareableFileRequestFromJSONTyped,
    HandlersShareableFileRequestToJSON,
    HandlersShareableFileRequestToJSONTyped,
} from './HandlersShareableFileRequest';
import type { HandlersCreateShareableRequestNotificationParams } from './HandlersCreateShareableRequestNotificationParams';
import {
    HandlersCreateShareableRequestNotificationParamsFromJSON,
    HandlersCreateShareableRequestNotificationParamsFromJSONTyped,
    HandlersCreateShareableRequestNotificationParamsToJSON,
    HandlersCreateShareableRequestNotificationParamsToJSONTyped,
} from './HandlersCreateShareableRequestNotificationParams';
import type { ServicesShareableType } from './ServicesShareableType';
import {
    ServicesShareableTypeFromJSON,
    ServicesShareableTypeFromJSONTyped,
    ServicesShareableTypeToJSON,
    ServicesShareableTypeToJSONTyped,
} from './ServicesShareableType';
import type { HandlersCreateShareableRequestTimeParams } from './HandlersCreateShareableRequestTimeParams';
import {
    HandlersCreateShareableRequestTimeParamsFromJSON,
    HandlersCreateShareableRequestTimeParamsFromJSONTyped,
    HandlersCreateShareableRequestTimeParamsToJSON,
    HandlersCreateShareableRequestTimeParamsToJSONTyped,
} from './HandlersCreateShareableRequestTimeParams';
import type { HandlersCreateShareableRequestParams } from './HandlersCreateShareableRequestParams';
import {
    HandlersCreateShareableRequestParamsFromJSON,
    HandlersCreateShareableRequestParamsFromJSONTyped,
    HandlersCreateShareableRequestParamsToJSON,
    HandlersCreateShareableRequestParamsToJSONTyped,
} from './HandlersCreateShareableRequestParams';

/**
 * 
 * @export
 * @interface HandlersCreateShareableRequest
 */
export interface HandlersCreateShareableRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof HandlersCreateShareableRequest
     */
    allowedEmails?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateShareableRequest
     */
    data?: string;
    /**
     * 
     * @type {Array<HandlersShareableFileRequest>}
     * @memberof HandlersCreateShareableRequest
     */
    files?: Array<HandlersShareableFileRequest>;
    /**
     * 
     * @type {string}
     * @memberof HandlersCreateShareableRequest
     */
    name: string;
    /**
     * 
     * @type {HandlersCreateShareableRequestNotificationParams}
     * @memberof HandlersCreateShareableRequest
     */
    notificationParams?: HandlersCreateShareableRequestNotificationParams;
    /**
     * 
     * @type {HandlersCreateShareableRequestParams}
     * @memberof HandlersCreateShareableRequest
     */
    options?: HandlersCreateShareableRequestParams;
    /**
     * 
     * @type {HandlersCreateShareableRequestTimeParams}
     * @memberof HandlersCreateShareableRequest
     */
    timeParams: HandlersCreateShareableRequestTimeParams;
    /**
     * 
     * @type {ServicesShareableType}
     * @memberof HandlersCreateShareableRequest
     */
    type: ServicesShareableType;
}



/**
 * Check if a given object implements the HandlersCreateShareableRequest interface.
 */
export function instanceOfHandlersCreateShareableRequest(value: object): value is HandlersCreateShareableRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('timeParams' in value) || value['timeParams'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function HandlersCreateShareableRequestFromJSON(json: any): HandlersCreateShareableRequest {
    return HandlersCreateShareableRequestFromJSONTyped(json, false);
}

export function HandlersCreateShareableRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateShareableRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedEmails': json['allowed_emails'] == null ? undefined : json['allowed_emails'],
        'data': json['data'] == null ? undefined : json['data'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(HandlersShareableFileRequestFromJSON)),
        'name': json['name'],
        'notificationParams': json['notification_params'] == null ? undefined : HandlersCreateShareableRequestNotificationParamsFromJSON(json['notification_params']),
        'options': json['options'] == null ? undefined : HandlersCreateShareableRequestParamsFromJSON(json['options']),
        'timeParams': HandlersCreateShareableRequestTimeParamsFromJSON(json['time_params']),
        'type': ServicesShareableTypeFromJSON(json['type']),
    };
}

export function HandlersCreateShareableRequestToJSON(json: any): HandlersCreateShareableRequest {
    return HandlersCreateShareableRequestToJSONTyped(json, false);
}

export function HandlersCreateShareableRequestToJSONTyped(value?: HandlersCreateShareableRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed_emails': value['allowedEmails'],
        'data': value['data'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(HandlersShareableFileRequestToJSON)),
        'name': value['name'],
        'notification_params': HandlersCreateShareableRequestNotificationParamsToJSON(value['notificationParams']),
        'options': HandlersCreateShareableRequestParamsToJSON(value['options']),
        'time_params': HandlersCreateShareableRequestTimeParamsToJSON(value['timeParams']),
        'type': ServicesShareableTypeToJSON(value['type']),
    };
}

