/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersMeResponse
 */
export interface HandlersMeResponse {
    /**
     * 
     * @type {string}
     * @memberof HandlersMeResponse
     */
    avatar?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersMeResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersMeResponse
     */
    id?: string;
}

/**
 * Check if a given object implements the HandlersMeResponse interface.
 */
export function instanceOfHandlersMeResponse(value: object): value is HandlersMeResponse {
    return true;
}

export function HandlersMeResponseFromJSON(json: any): HandlersMeResponse {
    return HandlersMeResponseFromJSONTyped(json, false);
}

export function HandlersMeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersMeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'email': json['email'] == null ? undefined : json['email'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function HandlersMeResponseToJSON(json: any): HandlersMeResponse {
    return HandlersMeResponseToJSONTyped(json, false);
}

export function HandlersMeResponseToJSONTyped(value?: HandlersMeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'email': value['email'],
        'id': value['id'],
    };
}

