/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersCreateShareableRequestParams
 */
export interface HandlersCreateShareableRequestParams {
    /**
     * 
     * @type {boolean}
     * @memberof HandlersCreateShareableRequestParams
     */
    encrypt?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HandlersCreateShareableRequestParams
     */
    onlyOnce?: boolean;
}

/**
 * Check if a given object implements the HandlersCreateShareableRequestParams interface.
 */
export function instanceOfHandlersCreateShareableRequestParams(value: object): value is HandlersCreateShareableRequestParams {
    return true;
}

export function HandlersCreateShareableRequestParamsFromJSON(json: any): HandlersCreateShareableRequestParams {
    return HandlersCreateShareableRequestParamsFromJSONTyped(json, false);
}

export function HandlersCreateShareableRequestParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersCreateShareableRequestParams {
    if (json == null) {
        return json;
    }
    return {
        
        'encrypt': json['encrypt'] == null ? undefined : json['encrypt'],
        'onlyOnce': json['only_once'] == null ? undefined : json['only_once'],
    };
}

export function HandlersCreateShareableRequestParamsToJSON(json: any): HandlersCreateShareableRequestParams {
    return HandlersCreateShareableRequestParamsToJSONTyped(json, false);
}

export function HandlersCreateShareableRequestParamsToJSONTyped(value?: HandlersCreateShareableRequestParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'encrypt': value['encrypt'],
        'only_once': value['onlyOnce'],
    };
}

