/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HandlersGoogleCallbackRequest
 */
export interface HandlersGoogleCallbackRequest {
    /**
     * 
     * @type {string}
     * @memberof HandlersGoogleCallbackRequest
     */
    code: string;
    /**
     * 
     * @type {string}
     * @memberof HandlersGoogleCallbackRequest
     */
    state: string;
}

/**
 * Check if a given object implements the HandlersGoogleCallbackRequest interface.
 */
export function instanceOfHandlersGoogleCallbackRequest(value: object): value is HandlersGoogleCallbackRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function HandlersGoogleCallbackRequestFromJSON(json: any): HandlersGoogleCallbackRequest {
    return HandlersGoogleCallbackRequestFromJSONTyped(json, false);
}

export function HandlersGoogleCallbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): HandlersGoogleCallbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'state': json['state'],
    };
}

export function HandlersGoogleCallbackRequestToJSON(json: any): HandlersGoogleCallbackRequest {
    return HandlersGoogleCallbackRequestToJSONTyped(json, false);
}

export function HandlersGoogleCallbackRequestToJSONTyped(value?: HandlersGoogleCallbackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'state': value['state'],
    };
}

