/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InternalErrorResponse
 */
export interface InternalErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof InternalErrorResponse
     */
    message?: string;
}

/**
 * Check if a given object implements the InternalErrorResponse interface.
 */
export function instanceOfInternalErrorResponse(value: object): value is InternalErrorResponse {
    return true;
}

export function InternalErrorResponseFromJSON(json: any): InternalErrorResponse {
    return InternalErrorResponseFromJSONTyped(json, false);
}

export function InternalErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InternalErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function InternalErrorResponseToJSON(json: any): InternalErrorResponse {
    return InternalErrorResponseToJSONTyped(json, false);
}

export function InternalErrorResponseToJSONTyped(value?: InternalErrorResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

