/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServicesShareableType = {
    ShareableTypeText: 'text',
    ShareableTypeURL: 'url',
    ShareableTypeFile: 'file'
} as const;
export type ServicesShareableType = typeof ServicesShareableType[keyof typeof ServicesShareableType];


export function instanceOfServicesShareableType(value: any): boolean {
    for (const key in ServicesShareableType) {
        if (Object.prototype.hasOwnProperty.call(ServicesShareableType, key)) {
            if (ServicesShareableType[key as keyof typeof ServicesShareableType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServicesShareableTypeFromJSON(json: any): ServicesShareableType {
    return ServicesShareableTypeFromJSONTyped(json, false);
}

export function ServicesShareableTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesShareableType {
    return json as ServicesShareableType;
}

export function ServicesShareableTypeToJSON(value?: ServicesShareableType | null): any {
    return value as any;
}

export function ServicesShareableTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): ServicesShareableType {
    return value as ServicesShareableType;
}

