/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServicesTargetUserEmails
 */
export interface ServicesTargetUserEmails {
    /**
     * 
     * @type {string}
     * @memberof ServicesTargetUserEmails
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServicesTargetUserEmails
     */
    isStarred?: boolean;
}

/**
 * Check if a given object implements the ServicesTargetUserEmails interface.
 */
export function instanceOfServicesTargetUserEmails(value: object): value is ServicesTargetUserEmails {
    return true;
}

export function ServicesTargetUserEmailsFromJSON(json: any): ServicesTargetUserEmails {
    return ServicesTargetUserEmailsFromJSONTyped(json, false);
}

export function ServicesTargetUserEmailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesTargetUserEmails {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'isStarred': json['is_starred'] == null ? undefined : json['is_starred'],
    };
}

export function ServicesTargetUserEmailsToJSON(json: any): ServicesTargetUserEmails {
    return ServicesTargetUserEmailsToJSONTyped(json, false);
}

export function ServicesTargetUserEmailsToJSONTyped(value?: ServicesTargetUserEmails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'is_starred': value['isStarred'],
    };
}

