/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServicesShareableSignedFile
 */
export interface ServicesShareableSignedFile {
    /**
     * 
     * @type {number}
     * @memberof ServicesShareableSignedFile
     */
    contentSize?: number;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableSignedFile
     */
    contentType?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableSignedFile
     */
    fileName?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableSignedFile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableSignedFile
     */
    shareID?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableSignedFile
     */
    signedURL?: string;
}

/**
 * Check if a given object implements the ServicesShareableSignedFile interface.
 */
export function instanceOfServicesShareableSignedFile(value: object): value is ServicesShareableSignedFile {
    return true;
}

export function ServicesShareableSignedFileFromJSON(json: any): ServicesShareableSignedFile {
    return ServicesShareableSignedFileFromJSONTyped(json, false);
}

export function ServicesShareableSignedFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesShareableSignedFile {
    if (json == null) {
        return json;
    }
    return {
        
        'contentSize': json['contentSize'] == null ? undefined : json['contentSize'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'fileName': json['fileName'] == null ? undefined : json['fileName'],
        'id': json['id'] == null ? undefined : json['id'],
        'shareID': json['shareID'] == null ? undefined : json['shareID'],
        'signedURL': json['signedURL'] == null ? undefined : json['signedURL'],
    };
}

export function ServicesShareableSignedFileToJSON(json: any): ServicesShareableSignedFile {
    return ServicesShareableSignedFileToJSONTyped(json, false);
}

export function ServicesShareableSignedFileToJSONTyped(value?: ServicesShareableSignedFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'contentSize': value['contentSize'],
        'contentType': value['contentType'],
        'fileName': value['fileName'],
        'id': value['id'],
        'shareID': value['shareID'],
        'signedURL': value['signedURL'],
    };
}

