/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServicesShareableType } from './ServicesShareableType';
import {
    ServicesShareableTypeFromJSON,
    ServicesShareableTypeFromJSONTyped,
    ServicesShareableTypeToJSON,
    ServicesShareableTypeToJSONTyped,
} from './ServicesShareableType';

/**
 * 
 * @export
 * @interface ServicesShareableCode
 */
export interface ServicesShareableCode {
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    activeFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    expiryAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ServicesShareableCode
     */
    options?: { [key: string]: string; };
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    shareableData?: string;
    /**
     * 
     * @type {ServicesShareableType}
     * @memberof ServicesShareableCode
     */
    shareableType?: ServicesShareableType;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    sourceIp?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    userEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof ServicesShareableCode
     */
    userID?: string;
}



/**
 * Check if a given object implements the ServicesShareableCode interface.
 */
export function instanceOfServicesShareableCode(value: object): value is ServicesShareableCode {
    return true;
}

export function ServicesShareableCodeFromJSON(json: any): ServicesShareableCode {
    return ServicesShareableCodeFromJSONTyped(json, false);
}

export function ServicesShareableCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServicesShareableCode {
    if (json == null) {
        return json;
    }
    return {
        
        'activeFrom': json['activeFrom'] == null ? undefined : json['activeFrom'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'expiryAt': json['expiryAt'] == null ? undefined : json['expiryAt'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'options': json['options'] == null ? undefined : json['options'],
        'shareableData': json['shareableData'] == null ? undefined : json['shareableData'],
        'shareableType': json['shareableType'] == null ? undefined : ServicesShareableTypeFromJSON(json['shareableType']),
        'sourceIp': json['sourceIp'] == null ? undefined : json['sourceIp'],
        'userEmail': json['userEmail'] == null ? undefined : json['userEmail'],
        'userID': json['userID'] == null ? undefined : json['userID'],
    };
}

export function ServicesShareableCodeToJSON(json: any): ServicesShareableCode {
    return ServicesShareableCodeToJSONTyped(json, false);
}

export function ServicesShareableCodeToJSONTyped(value?: ServicesShareableCode | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'activeFrom': value['activeFrom'],
        'createdAt': value['createdAt'],
        'expiryAt': value['expiryAt'],
        'id': value['id'],
        'name': value['name'],
        'options': value['options'],
        'shareableData': value['shareableData'],
        'shareableType': ServicesShareableTypeToJSON(value['shareableType']),
        'sourceIp': value['sourceIp'],
        'userEmail': value['userEmail'],
        'userID': value['userID'],
    };
}

