/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandlersGoogleCallbackRequest,
  HandlersGoogleCallbackResponse,
  HandlersGoogleLoginResponse,
  InternalErrorResponse,
} from '../models/index';
import {
    HandlersGoogleCallbackRequestFromJSON,
    HandlersGoogleCallbackRequestToJSON,
    HandlersGoogleCallbackResponseFromJSON,
    HandlersGoogleCallbackResponseToJSON,
    HandlersGoogleLoginResponseFromJSON,
    HandlersGoogleLoginResponseToJSON,
    InternalErrorResponseFromJSON,
    InternalErrorResponseToJSON,
} from '../models/index';

export interface AuthGoogleCallbackPostRequest {
    handlersGoogleCallbackRequest: HandlersGoogleCallbackRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Creates request options for authGoogleCallbackPost without sending the request
     */
    async authGoogleCallbackPostRequestOpts(requestParameters: AuthGoogleCallbackPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['handlersGoogleCallbackRequest'] == null) {
            throw new runtime.RequiredError(
                'handlersGoogleCallbackRequest',
                'Required parameter "handlersGoogleCallbackRequest" was null or undefined when calling authGoogleCallbackPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/auth/google/callback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandlersGoogleCallbackRequestToJSON(requestParameters['handlersGoogleCallbackRequest']),
        };
    }

    /**
     * Validates Google OAuth code and state, creates or retrieves user, sets access_token and refresh_token HttpOnly cookies.
     * Google OAuth callback
     */
    async authGoogleCallbackPostRaw(requestParameters: AuthGoogleCallbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersGoogleCallbackResponse>> {
        const requestOptions = await this.authGoogleCallbackPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersGoogleCallbackResponseFromJSON(jsonValue));
    }

    /**
     * Validates Google OAuth code and state, creates or retrieves user, sets access_token and refresh_token HttpOnly cookies.
     * Google OAuth callback
     */
    async authGoogleCallbackPost(requestParameters: AuthGoogleCallbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersGoogleCallbackResponse> {
        const response = await this.authGoogleCallbackPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authGoogleLoginGet without sending the request
     */
    async authGoogleLoginGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/auth/google/login`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Generates OAuth state, stores it in HttpOnly cookie, and returns Google authorization URL.
     * Initiate Google OAuth login
     */
    async authGoogleLoginGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersGoogleLoginResponse>> {
        const requestOptions = await this.authGoogleLoginGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersGoogleLoginResponseFromJSON(jsonValue));
    }

    /**
     * Generates OAuth state, stores it in HttpOnly cookie, and returns Google authorization URL.
     * Initiate Google OAuth login
     */
    async authGoogleLoginGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersGoogleLoginResponse> {
        const response = await this.authGoogleLoginGetRaw(initOverrides);
        return await response.value();
    }

}
