/* tslint:disable */
/* eslint-disable */
/**
 * eev-backend
 * Backend service for eev
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@alenalex.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HandlersCreateShareableRequest,
  HandlersCreateShareableResponse,
  InternalErrorResponse,
  ServicesShareableCode,
} from '../models/index';
import {
    HandlersCreateShareableRequestFromJSON,
    HandlersCreateShareableRequestToJSON,
    HandlersCreateShareableResponseFromJSON,
    HandlersCreateShareableResponseToJSON,
    InternalErrorResponseFromJSON,
    InternalErrorResponseToJSON,
    ServicesShareableCodeFromJSON,
    ServicesShareableCodeToJSON,
} from '../models/index';

export interface ShareCodeGetRequest {
    code: string;
}

export interface SharePostRequest {
    handlersCreateShareableRequest: HandlersCreateShareableRequest;
}

/**
 * 
 */
export class ShareableApi extends runtime.BaseAPI {

    /**
     * Creates request options for shareCodeGet without sending the request
     */
    async shareCodeGetRequestOpts(requestParameters: ShareCodeGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['code'] == null) {
            throw new runtime.RequiredError(
                'code',
                'Required parameter "code" was null or undefined when calling shareCodeGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/share/{code}`;
        urlPath = urlPath.replace(`{${"code"}}`, encodeURIComponent(String(requestParameters['code'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves public shareable information using its unique code.
     * Get shareable by code
     */
    async shareCodeGetRaw(requestParameters: ShareCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServicesShareableCode>> {
        const requestOptions = await this.shareCodeGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServicesShareableCodeFromJSON(jsonValue));
    }

    /**
     * Retrieves public shareable information using its unique code.
     * Get shareable by code
     */
    async shareCodeGet(requestParameters: ShareCodeGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServicesShareableCode> {
        const response = await this.shareCodeGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sharePost without sending the request
     */
    async sharePostRequestOpts(requestParameters: SharePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['handlersCreateShareableRequest'] == null) {
            throw new runtime.RequiredError(
                'handlersCreateShareableRequest',
                'Required parameter "handlersCreateShareableRequest" was null or undefined when calling sharePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/share`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: HandlersCreateShareableRequestToJSON(requestParameters['handlersCreateShareableRequest']),
        };
    }

    /**
     * Creates a new shareable resource (text, url, or file). Requires authentication via access_token cookie.
     * Create a new shareable
     */
    async sharePostRaw(requestParameters: SharePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HandlersCreateShareableResponse>> {
        const requestOptions = await this.sharePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HandlersCreateShareableResponseFromJSON(jsonValue));
    }

    /**
     * Creates a new shareable resource (text, url, or file). Requires authentication via access_token cookie.
     * Create a new shareable
     */
    async sharePost(requestParameters: SharePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HandlersCreateShareableResponse> {
        const response = await this.sharePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
